title: Инвестирование и финансовая независимость
email: contact@capital-gain.ru
description: >- # this means to ignore newlines until "baseurl:"
  От автора инструментов инвестора на Capital-Gain.ru
  и книги «Речь о миллионах».
lang: ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/posts/:slug/"
telegram_username: capitalgainru
locale: ru
timezone: Asia/Omsk
show_excerpts: true
# GitHub Pages defaults
lsi: false
safe: true
source: "./"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# End of GitHub Pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
