title: Дмитрий Никитенко
email: contact@capital-gain.ru
description: >-
  Блог о пассивном инвестировании по стратегии распределения активов
  и финансовой независимости. Полезные инструменты для инвесторов.
tagline: Инвестирование и финансовая независимость
lang: ru
locale: ru_RU
logo: /assets/logo-512.png
url: 'https://capital-gain.ru'
baseurl: ''
permalink: '/posts/:slug/'
timezone: Asia/Omsk
show_excerpts: true
telegram_username: capitalgainru
vk_username: capitalgain
dzen_username: capitalgain
github_username: nDmitry
rss: Atom
# GitHub Pages defaults
lsi: false
safe: true
source: './'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  smart_quotes: bdquo,ldquo,laquo,raquo
# End of GitHub Pages
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      title: ''
      excerpt: ''
      author: 'Дмитрий Никитенко'
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 10
paginate_path: '/page/:num/'
seo_paginator_message: 'Страница %{current} из %{total} | '
counter_id: 56626909
