title: Дмитрий Никитенко
email: contact@capital-gain.ru
description: >-
  Блог о пассивном инвестировании по стратегии распределения активов
  и финансовой независимости. Полезные инструменты для инвесторов.
tagline: Инвестирование и финансовая независимость
lang: ru
locale: ru_RU
logo: /assets/logo-512.png
url: 'https://capital-gain.ru'
baseurl: ''
permalink: '/posts/:slug/'
timezone: Asia/Omsk
show_excerpts: true
telegram_username: capitalgainru
vk_username: capitalgain
dzen_username: capitalgain
substack_username: capitalgainru
rss: Atom
kramdown:
  math_engine: katex
  math_engine_opts:
    delimiters:
      - {left: '$$', right: '$$', display: true}
  syntax_highlighter: rouge
  smart_quotes: bdquo,ldquo,laquo,raquo
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      title: ''
      excerpt: ''
      author: 'Дмитрий Никитенко'
sass:
  style: compressed
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 10
paginate_path: '/page/:num/'
seo_paginator_message: 'Страница %{current} из %{total} | '
counter_id: 56626909
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  slug_mode: pretty
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
